name: Publish Docker

on:
  release:
      types: [published]
  push:
    branches:
      - develop

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@master
    - name: Get the release version
      run: .github/scripts/publish-docker.bash
    - name: Publish to Registry (with a tagged image)
      if: ${{ env.PUBLISH_RELEASE_VERSION == 'true' }}
      run: |
        podman build --squash-all -t image .
        echo ${{ secrets.GHCR_PAT }} | podman login ghcr.io -u ${{ github.actor }} --password-stdin
        podman push image ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
        podman push image ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ env.RELEASE_VERSION }}
    - name: Publish to Registry (without a tagged image)
      if: ${{ env.PUBLISH_RELEASE_VERSION == 'false' }}
      run: |
        podman build --squash-all -t image .
        echo ${{ secrets.GHCR_PAT }} | podman login ghcr.io -u ${{ github.actor }} --password-stdin
        podman push image ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest